vars:
  - raw_data_zip: ./data/raw/made-cv-2021-contest-02-license-plate-recognition.zip
  - train_dir: ./data/converted

stages:
  downloda-data:
    cmd:
      kaggle competitions download --force -c made-cv-2021-contest-02-license-plate-recognition
      -p ./data/raw
    outs:
      - ${raw_data_zip}:
          cache: true
          persist: true
  convert_images:
    cmd: python ./convert_images.py -cd ./configs
    deps:
      - ./convert_images.py
      - ./config_data/convert_config.py
      - ./configs/convert_images.yaml
      - ${raw_data_zip}
    outs:
      - ${train_dir}:
          cache: true
          persist: true
  train-detector:
    cmd: python ./train_plate_detector.py -cd ./configs exp_dir=./exp/detector
    deps:
      - ${train_dir}
      - ./configs/train_detector.yaml
      - ./configs/detector/detector_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./configs/scheduler/plato.yaml
      - ./train_plate_detector.py
      - ./model/plate_detector.py
      - ./dataset/plates_data.py
      - ./dataset/plates_module.py
      - ./transforms/transforms.py
    outs:
      - ./exp/detector
