vars:
  - raw_data_zip: ./data/raw/made-cv-2021-contest-02-license-plate-recognition.zip
  - train_dir: ./data/raw/made-cv-2021-contest-02-license-plate-recognition

stages:
  downloda-data:
    cmd:
      kaggle competitions download --force -c made-cv-2021-contest-02-license-plate-recognition
      -p ./data/raw
    outs:
      - ${raw_data_zip}:
          cache: true
          persist: true
  unzip:
    cmd: python -m zipfile -e ${raw_data_zip} ${train_dir}
    deps:
      - ${raw_data_zip}
    outs:
      - ${train_dir}:
          cache: false
          persist: true
  train-detector:
    cmd: python ./train_plate_detector.py -cd ./configs exp_dir=./exp/detector
    deps:
      - ${train_dir}
      - ./configs/train_config.yaml
      - ./configs/detector/detector_base.yaml
      - ./configs/optimizer/adam.yaml
      - ./scheduler/plato.yaml
      - ./train_plate_detector.py
      - ./models/plate_detector.py
      - ./dataset/plates_data.py
      - ./dataset/plates_modules.py
      - ./transforms/transforms.py
    outs:
      - ./exp/detector
