defaults:
  - detector: detector_base
  - ocr_config: null
  - optimizer: adam
  - scheduler: plato

data_dir: ./data/raw/made-cv-2021-contest-02-license-plate-recognition/data
train_size: 0.9
seed: 43
num_workers: 4
check_val_every_n_epoch: 1
max_epochs: 2
flush_logs_every_n_steps: 20
val_check_interval: 100
max_image_size: 600
