defaults:
  - detector: detector_base
  - ocr_config: null
  - optimizer: adam
  - scheduler: null

data_dir: ./data/raw/contest02_data/data
train_size: 0.9
seed: 43
num_workers: 4
exp_dir: ./exp
check_val_every_n_epoch: 1
max_epochs: 5
flush_logs_every_n_steps: 20
